### ISSUE TITLE
Dollar sign escaping and # inside code blocks.

### ISSUE THREAD

**Issue by Macmod** [Moeditor/Moeditor#37] opened 2016-07-29 04:14 UTC
The dollar sign isn't being escaped when writing \$.
Also, writing # inside a code block (indented with 4 spaces) formats the text as a title on the left side, whereas it should be just a comment.

EDIT: The latter doesn't happen with code blocks made of backticks, although it shouldn't happen at all.

**Comment by Menci** [comment] 2016-07-31 16:39
Closed as duplicate of #5.

**Closed by Menci** 2016-07-31 16:39 UTC
