### ISSUE TITLE
Preview doesn't stay inline with markdown

### ISSUE THREAD

**Issue by OmgImAlexis** [Moeditor/Moeditor#14] opened 2016-07-10 15:12 UTC
[Here's a sample](https://gist.githubusercontent.com/OmgImAlexis/99e2c83bade4bcc9305bb92c35739cb7/raw/5ba92544f7ed73486365ce0e41f14c0920d0b921/gistfile1.txt) that I was using to test Moeditor for bugs when I found this issue.
It also doesn't inline code such as \`$1.alete.xyz\`

![screen shot 2016-07-10 at 4 09 02 pm](https://cloud.githubusercontent.com/assets/6525926/16714371/b17a0f92-46b8-11e6-82ca-7f05c38f995a.png)

**Comment by Menci** [comment] 2016-07-10 15:54
Duplicate of #5?

**Comment by OmgImAlexis** [comment] 2016-07-10 20:04
@Menci possibly but even if it was rendering it properly it should still track the markdown and preview to around the same area. Even in fullscreen it's still not even close.

**Comment by Menci** [comment] 2016-07-10 23:07
Oh, you mean the sync scroll? Maybe duplicate of #7? I have writeen a better algorithm(but isn't perfect) in recent commits, you can try to clone by git and build.

However, I think the rendering is wrong, too. `$` in code will be treat as math. This was (half) fixed in a recent commit, but the editor's highlight is still wrong. See #5.

**Comment by OmgImAlexis** [comment] 2016-07-11 21:23
Yep it looks like it may be similar or the same as #7

**Comment by Menci** [comment] 2016-07-11 23:44
So I'll close it as duplicate.

**Closed by Menci** 2016-07-11 23:44 UTC
