### ISSUE TITLE
Need more accurate synchronized scrolling

### ISSUE THREAD

**Issue by kdepp** [Moeditor/Moeditor#10] opened 2016-07-07 12:10 UTC
The scrolling is now synchronized just by offset percentage. The mismatch will grow while more and more images are added to the mdl

**Comment by tmr232** [comment] 2016-07-07 13:14
Duplicate of #7 ?

**Comment by Menci** [comment] 2016-07-07 15:20
Duplicate of #7.

**Closed by Menci** 2016-07-07 15:20 UTC
