### ISSUE TITLE
TeX parse error

### ISSUE THREAD

**Issue by medikoo** [Moeditor/Moeditor#8] opened 2016-07-06 07:11 UTC
When trying to view this file -> https://github.com/medikoo/memoizee/blob/master/README.md

In Installation section I got:
```
TeX parse error: You can't use 'macro parameter character #' in math mode 
```

Screenshot:

![screen shot 2016-07-06 at 09 10 59](https://cloud.githubusercontent.com/assets/122434/16610124/93f391ee-4359-11e6-998b-af40e646fc46.png)

**Comment by Menci** [comment] 2016-07-06 10:59
A duplicate of #5.

---

It seems your project is a great cache lib, I wonder if I can replace [lrucache](https://github.com/zensh/lrucache) with your [medikoo](https://github.com/medikoo/memoizee) for rendered math and highlighted code. Maybe we can discuss that in somewhere else.

**Closed by Menci** 2016-07-06 10:59 UTC
Labels: bug, duplicate

**Comment by medikoo** [comment] 2016-07-06 11:08
> It seems your project is a great cache lib, I wonder if I can replace lrucache with your medikoo for rendered math and highlighted code. Maybe we can discuss that in somewhere else.

Sure, don't hesitate to contact me if you have some questions
